namespace: production

apigateway:
  image: 565393062704.dkr.ecr.eu-west-3.amazonaws.com
  version: 1.0.35
  replicaCount: 2

customersservice:
  image: 565393062704.dkr.ecr.eu-west-3.amazonaws.com
  version: 1.0.35
  replicaCount: 1

vetsservice:
  image: 565393062704.dkr.ecr.eu-west-3.amazonaws.com
  version: 1.0.35
  replicaCount: 1

visitsservice:
  image: 565393062704.dkr.ecr.eu-west-3.amazonaws.com
  version: 1.0.35
  replicaCount: 1

database:
  host: petclinic-db.c9mu0cykmyng.eu-west-3.rds.amazonaws.com:3306
  name: petclinicdb
  username: petclinic
  password: redacted
