namespace: production

apigateway:
  image: 472454369658.dkr.ecr.eu-west-3.amazonaws.com/petclinic/api-gateway
  version: 1.0.34
  replicaCount: 2

customersservice:
  image: 472454369658.dkr.ecr.eu-west-3.amazonaws.com/petclinic/customers-service
  version: 1.0.34
  replicaCount: 1

vetsservice:
  image: 472454369658.dkr.ecr.eu-west-3.amazonaws.com/petclinic/vets-service
  version: 1.0.34
  replicaCount: 1

visitsservice:
  image: 472454369658.dkr.ecr.eu-west-3.amazonaws.com/petclinic/visits-service
  version: 1.0.34
  replicaCount: 1

database:
  host: petclinic-db.cxiuqiwk8irr.eu-west-3.rds.amazonaws.com:3306
  name: petclinicdb
  username: petclinic
  password: redacted
  # password: '{"data":{"password":"cGV0Y2xpbmljZGJwYXNzd29yZA=="}}